### ISSUE TITLE
Slow startup under Wayland

### ISSUE THREAD

**Issue by Jiogo18** [EnditTeam/Interville-Launcher#2]
The launcher takes 55 seconds to start.
The gray window is visible after 35 seconds.

I am using the AppImage 1.0.2 under Wayland

**Comment by simon511000** [comment]
I think it's a packaging issue. I don't encounter this problem with the development version (`npm run start`).
I'll investigate further.

**Comment by simon511000** [comment]
I can confirm it's a packaging issue that occurs when the compression of the AppImage is set to maximum.
Upstream issue: https://github.com/electron-userland/electron-builder/issues/6317
